INSERT INTO CATEGORIA(ID, NOME)
VALUES(NEWID(), 'Salário e Renda')
GO

INSERT INTO CATEGORIA(ID, NOME)
VALUES(NEWID(), 'Despesas de Casa')
GO

INSERT INTO CATEGORIA(ID, NOME)
VALUES(NEWID(), 'Alimentação')
GO

INSERT INTO CATEGORIA(ID, NOME)
VALUES(NEWID(), 'Saúde / Despesas médicas')
GO

INSERT INTO CATEGORIA(ID, NOME)
VALUES(NEWID(), 'Lazer / Viagens')
GO

INSERT INTO CATEGORIA(ID, NOME)
VALUES(NEWID(), 'Cursos / Faculdade')
GO

INSERT INTO CATEGORIA(ID, NOME)
VALUES(NEWID(), 'Outros')
GO

SELECT * FROM CATEGORIA;